#+title: bisos.dockerProc: Facilities for Creating and Managing Vagrant Packer Base Boxes
#+DATE: <2024-02-19 Mon 16:27>
#+AUTHOR: Mohsen BANAN
#+OPTIONS: toc:4

#+BEGIN: b:org:pypi:readme/topControls :pkgName "dockerProc" :comment "basic"

|----------------------+------------------------------------------------------------------|
| ~Blee Panel Controls~: | [[elisp:(show-all)][Show-All]] : [[elisp:(org-shifttab)][Overview]] : [[elisp:(progn (org-shifttab) (org-content))][Content]] : [[elisp:(delete-other-windows)][(1)]] : [[elisp:(progn (save-buffer) (kill-buffer))][S&Q]] : [[elisp:(save-buffer)][Save]]  : [[elisp:(kill-buffer)][Quit]]  : [[elisp:(bury-buffer)][Bury]] |
| ~Panel Links~:         | [[file:./py3/panels/bisos.facter/_nodeBase_/fullUsagePanel-en.org][Repo Blee Panel]] --  [[file:/bisos/git/auth/bxRepos/bisos-pip/facter/py3/panels/bisos.facter/_nodeBase_/fullUsagePanel-en.org][Blee Panel]]                                                |
| ~See Also~:            | [[https://pypi.org/project/bisos.facter][At PYPI]] : [[https://github.com/bisos-pip/pycs][bisos.PyCS]]                                             |
|----------------------+------------------------------------------------------------------|

#+END:

* Overview

/bisos.dockerProc/ provides various facilities for creation and management of
Vagrant Packer Base Boxes.

/bisos.dockerProc/ is a python package that uses the [[https://github.com/bisos-pip/pycs][PyCS-Framework]] for its
implementation. It is a BISOS-Capability and a Standalone-BISOS-Package.

/bisos.dockerProc/ is data driven. By itself it is incomplete. It operates
on well structured directories which contain packer base box specifications.
Separating packer specifications from the bisos.dockerProc package allows
for wide usage and expansion. BISOS-related packer specifications that can be
processed with bisos.dockerProc are available at:\\
[[https://github.com/bxObjects/bro_vagrantDebianBaseBoxes]]

#+BEGIN: b:org:pypi:readme/pkgDocumentation :pkgName "capability-cs" :comment "basic"

# PYPI Documentation Comes Here in _description.org
#+END:


* Table of Contents     :TOC:
- [[#overview][Overview]]
- [[#a-standalone-piece-of-bisos-----bystar-internet-services-operating-system][A Standalone Piece of BISOS --- ByStar Internet Services Operating System]]
- [[#prior-art-and-similar-art][Prior Art and Similar Art]]
  - [[#bisos-vagrant-debian-base-boxes-packer-specifications][BISOS Vagrant Debian Base Boxes Packer Specifications]]
- [[#installation-of-bisosdockerproc-package][Installation of bisos.dockerProc Package]]
  - [[#installation-with-pip][Installation With pip]]
  - [[#installation-with-pipx][Installation With pipx]]
- [[#usage-of-bisosdockerproc-package][Usage of bisos.dockerProc Package]]
  - [[#first-install-the-packer-box-specifications][First, Install the packer box specifications]]
  - [[#vagrantboxproccs-menu][vagrantBoxProc.cs Menu]]
- [[#bisos-use-of-built-vagrant-boxes][BISOS Use of Built Vagrant Boxes]]
- [[#best-developed-with-blee][Best Developed With Blee]]
- [[#some-relevant-pointers][Some Relevant Pointers]]
- [[#support][Support]]

* A Standalone Piece of BISOS --- ByStar Internet Services Operating System

Layered on top of Debian, [[https://github.com/bisos][BISOS]]: (By* Internet Services Operating System) is a
unified and universal framework for developing both internet services and
software-service continuums that use internet services. See [[https://github.com/bxGenesis/start][Bootstrapping
ByStar, BISOS and Blee]] for additional information.
*BISOS* is a foundation for [[https://github.com/mohsenBanan][The Libre-Halaal ByStar Digital Ecosystem]] which is
described as a cure for losses of autonomy and privacy in a book titled: [[https://github.com/bxplpc/120033][Nature
of Polyexistentials]].

bisos.dockerProc is a standalone piece of BISOS. It can be used as a self-contained
Python package separate from BISOS. Follow the installation and usage
instructions below for your own use.

* Prior Art and Similar Art

Use of Vagrant Base Boxes is quite common.

The model of using existing base boxes by downloading them from the web is
problematic for us, as it involves a level of trust which we consider unnecessary.
Hashicorp provides a collection of boxes at:\\
https://developer.hashicorp.com/vagrant/docs/boxes

Many others, like us prefer to always build their own boxes. Many open-source
projects and individual developers host their Vagrantfile configurations and
associated files (like provisioning scripts) on GitHub. These repositories allow
others to easily replicate their testing, development or production environments.
Bento, Boxcutter, osboxes and Veewee are just few examples on github.
See "Some Relevant Pointers" section below for more.

We want to consolidate and canonicalize building of vagrant base boxes to avoid
duplication and to improve quality of the boxes.

For Debian, https://github.com/rgl/debian-vagrant provides a number of base
boxes. Much of /bisos.dockerProc/ and bxObjects/bro_vagrantDebianBaseBoxe is
based on that but our general data driven approach is different.


** BISOS Vagrant Debian Base Boxes Packer Specifications


In BISOS, the packer base box specifications are in the form of a
BISOS Repo Object (BRO). In BISOS, the defaults are:

#+begin_src bash
cd /bisos/git/bxRepos/bxObjects
git clone https://github.com/bxObjects/bro_vagrantDebianBaseBoxes.git
#+end_src

Of course, you can clone that repo anywhere (the /bisos/git/bxRepos/bxObjects is
BISOS specific) and then just adjust the command line path to it when running
vagrantBoxProc.cs.

* Installation of bisos.dockerProc Package

The sources for the bisos.dockerProc pip package are maintained at:
https://github.com/bisos-pip/dockerProc.

The bisos.dockerProc pip package is available at PYPI as
https://pypi.org/project/bisos.dockerProc

You can install bisos.dockerProc with pip or pipx.

** Installation With pip

If you need access to bisos.dockerProc as a python module, you can install it with pip:

#+begin_src bash
pip install bisos.dockerProc
#+end_src

See below for this packages list of commands.

** Installation With pipx

If you only need access to bisos.dockerProc on command-line, you can install it with pipx:

#+begin_src bash
pipx install bisos.dockerProc
#+end_src

The following commands are made available:
- dockerProc-sbom.cs  (Software Bill of Material for vagrant and packer)
- vagrantBoxProc.cs  (The primary command line for building, adding, running and cleaning base boxes which is also a seed for vagBox.cs)
- exmpl-vagBox.cs    (Example for planting based on the vagrantBoxProc.cs as seed.)
- vagrantCommonCmnds.cs  (A cheat sheet for common vagrant commands.)

* Usage of bisos.dockerProc Package

** First, Install the packer box specifications

Clone the packer box specifications somewhere. Perhaps in your home directory.

#+begin_src bash
git clone https://github.com/bxObjects/bro_vagrantDebianBaseBoxes.git
#+end_src

For BISOS we use the /bisos/git/bxRepos/bxObjects canonical directory as a base for cloning bro_vagrantDebianBaseBoxes.

** vagrantBoxProc.cs Menu

Run:

#+begin_src bash
vagrantBoxProc.cs
#+end_src

Without any parameters and arguments, vagrantBoxProc.cs gives you a menu of
common invokations.


* BISOS Use of Built Vagrant Boxes

In BISOS, we start from a Debian Vagrant Box which we consider as "fresh Debian" and we augment it to
to become "Raw-BISOS". This process is described in: https://github.com/bxgenesis/start

Based on a platform BPO (ByStar Portable Object), Raw-BISOS can then be further augmented to become a
reproducible specific BISOS-Platform.

* Best Developed With Blee

[[https://github.com/bx-blee][Blee]]", /By* BISOS Libre-Halaal Emacs Environment/
is a layer on top of Emacs and BISOS which creates a
comprehensive integrated usage and development environment. Blee and BISOS are intertwined.
This python package is developed with Blee. Its evolution is best accomplished
through continued use of Blee.

* Some Relevant Pointers

Some relevant pointers are included:

| *Resource*                     | *Link*                                                                                   |
|--------------------------------+------------------------------------------------------------------------------------------|
| Vagrant Cloud by HashiCorp     | [[https://app.vagrantup.com/][Vagrant Cloud]]                                            |
| Bento                          | [[https://github.com/chef/bento][Bento on GitHub]]                                       |
| Boxcutter                      | [[https://github.com/boxcutter][Boxcutter on GitHub]]                                    |
| Veewee                         | [[https://github.com/jedi4ever/veewee][Veewee on GitHub]]                                |
| Packer Templates by Parallels  | [[https://github.com/Parallels/vagrant-parallels][Parallels Packer Templates]]           |
| osboxes.org                    | [[https://www.osboxes.org/][osboxes.org]]                                                |
| Vagrant Setup by Jeff Geerling | [[https://github.com/geerlingguy/packer-boxes][Jeff Geerling's Vagrant Setup on GitHub]] |
| rgl/debian-vagrant             | https://github.com/rgl/debian-vagrant                                                    |


* Support

For support, criticism, comments, and questions, please contact the
author/maintainer\\
[[http://mohsen.1.banan.byname.net][Mohsen Banan]] at:
[[http://mohsen.1.banan.byname.net/contact]]


# Local Variables:
# eval: (setq-local toc-org-max-depth 4)
# End:
